version: "3.9"

services:
  go-typst-pdf:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # HTTP server
      - "50051:50051" # gRPC server
    volumes:
      - ./pdf:/app/pdf # Mount the pdf directory for persistence
      - ./static:/app/static # Mount the static directory
      - ./templates:/app/pdf/templates # Mount the templates directory
    restart: unless-stopped
  typst-cli:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 30; done;"]
    volumes:
      - ./pdf:/app/pdf
      - ./static:/app/static
      - ./templates:/app/pdf/templates
    working_dir: /app
    depends_on:
      - go-typst-pdf
    restart: unless-stopped