// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/pdf.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PDFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDFRequest) Reset() {
	*x = PDFRequest{}
	mi := &file_proto_pdf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDFRequest) ProtoMessage() {}

func (x *PDFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pdf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDFRequest.ProtoReflect.Descriptor instead.
func (*PDFRequest) Descriptor() ([]byte, []int) {
	return file_proto_pdf_proto_rawDescGZIP(), []int{0}
}

func (x *PDFRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *PDFRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type PDFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDFResponse) Reset() {
	*x = PDFResponse{}
	mi := &file_proto_pdf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDFResponse) ProtoMessage() {}

func (x *PDFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pdf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDFResponse.ProtoReflect.Descriptor instead.
func (*PDFResponse) Descriptor() ([]byte, []int) {
	return file_proto_pdf_proto_rawDescGZIP(), []int{1}
}

func (x *PDFResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_pdf_proto protoreflect.FileDescriptor

const file_proto_pdf_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/pdf.proto\x12\x05proto\"\x92\x01\n" +
	"\n" +
	"PDFRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12/\n" +
	"\x04data\x18\x02 \x03(\v2\x1b.proto.PDFRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\vPDFResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2B\n" +
	"\n" +
	"PDFService\x124\n" +
	"\vGeneratePDF\x12\x11.proto.PDFRequest\x1a\x12.proto.PDFResponseB\x14Z\x12go-typst-pdf/protob\x06proto3"

var (
	file_proto_pdf_proto_rawDescOnce sync.Once
	file_proto_pdf_proto_rawDescData []byte
)

func file_proto_pdf_proto_rawDescGZIP() []byte {
	file_proto_pdf_proto_rawDescOnce.Do(func() {
		file_proto_pdf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pdf_proto_rawDesc), len(file_proto_pdf_proto_rawDesc)))
	})
	return file_proto_pdf_proto_rawDescData
}

var file_proto_pdf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_pdf_proto_goTypes = []any{
	(*PDFRequest)(nil),  // 0: proto.PDFRequest
	(*PDFResponse)(nil), // 1: proto.PDFResponse
	nil,                 // 2: proto.PDFRequest.DataEntry
}
var file_proto_pdf_proto_depIdxs = []int32{
	2, // 0: proto.PDFRequest.data:type_name -> proto.PDFRequest.DataEntry
	0, // 1: proto.PDFService.GeneratePDF:input_type -> proto.PDFRequest
	1, // 2: proto.PDFService.GeneratePDF:output_type -> proto.PDFResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pdf_proto_init() }
func file_proto_pdf_proto_init() {
	if File_proto_pdf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pdf_proto_rawDesc), len(file_proto_pdf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pdf_proto_goTypes,
		DependencyIndexes: file_proto_pdf_proto_depIdxs,
		MessageInfos:      file_proto_pdf_proto_msgTypes,
	}.Build()
	File_proto_pdf_proto = out.File
	file_proto_pdf_proto_goTypes = nil
	file_proto_pdf_proto_depIdxs = nil
}
