name: Changelog Creator
run-name: ${{ github.actor }} is creating a changelog 🚀

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  Changelog-Creator:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Get Changelog
        id: changelog
        run: |
          BODY=$(gh pr view ${{ github.event.number }} --json body -q ".body")
          CHANGELOG=$(echo "$BODY" | awk '/## Release Changelog/{flag=1;next}/^## /{flag=0}flag')
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"

      - name: Create and commit Changelog
        run: |
          echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "Changelog for PR #${{ github.event.number }}"
          git push
